### ISSUE TITLE
Snapshot and final stage add a commit count on the calculated version 

### ISSUE THREAD

**Issue by briansurratt** [nefilim/gradle-semver-plugin#24]
The workflow I'm trying to set up is a follows:

|  trigger  |  scope | stage  |  last semver tag | expected | actual |
|---|---|---|---|---|---|
|  PR to develop | patch  |  snapshot  | 0.11.0  | 0.11.1-SNAPSHOT  | 0.11.1-SNAPSHOT.5 | 
|  push to develop  | patch  | final  | 0.11.0  |  0.11.1 | 0.11.1-1 |
| build main | minor | final | 0.11.0 | 0.12.0 | 0.12.0 |

The push to develop behavior was observed when on the HEAD of that branch, with the previous SEMVER tag being on the immediately preceeding commit.

I can see the value in the commit count for the alpha, beta and RC stages, but I think the SNAPSHOT and final stages the commit count is not important.  If I'm using the plugin in an unintended way, can you clarify the process you're implementing or support suppressing the commit counter entirely?  Thanks.

**Comment by nefilim** [comment]
Thanks for the report @briansurratt - I agree with your assessment, I think I introduced a regression, I'll release a fix this weekend.

**Comment by nefilim** [comment]
@briansurratt took a quick stab at it, released `0.1.8` - it will probably take a minute to propagate on maven central but should be available on gradle plugin portal, could you please give it a test?

**Comment by briansurratt** [comment]
Thanks for the wicked fast turn around. I will give it a shot in little bit

**Comment by briansurratt** [comment]
I upgraded to 0.1.8 and everything looks like it works as expected. I will finish building out my pipeline and give final confirmation.

Thanks again for the great support!

**Comment by nefilim** [comment]
you bet! thanks again for reporting the issue and giving the plugin a whirl 😄
