### ISSUE TITLE
Can't run on tag branch such as `v1.0.1`

### ISSUE THREAD

**Issue by SettingDust** [nefilim/gradle-semver-plugin#26]
https://github.com/EpicBanItemTeam/EpicBanItem/runs/6663532126?check_suite_focus=true#step%3A5%3A14=

**Comment by nefilim** [comment]
not really sure what you are trying to do, it doesn't make sense to push a versioned tag like that. please make sure you understand how git flow works, example: https://www.atlassian.com/git/tutorials/comparing-workflows/gitflow-workflow

recommend you push your changes on feature or develop branch, then merge to main for releases, see simple workflow examples here: https://github.com/nefilim/kjwt/tree/main/.github/workflows

**Comment by SettingDust** [comment]
I want to run the workflow when tagged like `vx.x.x`. So the workflow run on `vx.x.x`. It's not my push. 
My workflow will tag semver when push to `main`(merge `develop`). 
The workflow is triggered by 
```
on:
  push:
    tags:
      - v[0-9]+.[0-9]+.[0-9]+
```
It will run on the tag instead of the `main` branch. 

![图片](https://user-images.githubusercontent.com/19922286/171319202-a637c144-3ec9-42d2-be51-5575dcb774d3.png)

**Comment by nefilim** [comment]
can you please run gradle with `-i --stacktrace` - i'm not sure what's going wrong without more logging

**Comment by SettingDust** [comment]
> can you please run gradle with `-i --stacktrace` - i'm not sure what's going wrong without more logging

https://github.com/EpicBanItemTeam/EpicBanItem/runs/6701309313?check_suite_focus=true#step%3A5%3A30=

**Comment by nefilim** [comment]
sorry, don't think the plugin will be able to support this use case, the source is checked out in a detached head state, there is no branch. 

it doesn't really make sense to do another version calculation on a tag for release - what should the result be? if it should remain v1.0.1 you can script something that parses the current version from workflow target (v1.0.1) and pass that to gradle with `-Dsemver.overrideVersion=1.0.1` or whatever you configured your properties to be (see https://github.com/nefilim/gradle-semver-plugin#usage)

**Comment by SettingDust** [comment]
The override not working
```
semver {
    tagPrefix("v")
    initialVersion("1.0.0")
    findProperty("semver.overrideVersion")?.toString()?.let { overrideVersion(it) }
}
```
Output of `gradle cv -Dsemver.overrideVersion=1.0.1`
```
semver: enabling Git Flow mode
semver: current branch: Branch(name=develop, refName=refs/heads/develop)
semver: 1.0.4-beta.0

> Task :cv
version: 1.0.4-beta.0
```

**Comment by SettingDust** [comment]
> The override not working
> 
> ```
> semver {
>     tagPrefix("v")
>     initialVersion("1.0.0")
>     findProperty("semver.overrideVersion")?.toString()?.let { overrideVersion(it) }
> }
> ```
> 
> Output of `gradle cv -Dsemver.overrideVersion=1.0.1`
> 
> ```
> semver: enabling Git Flow mode
> semver: current branch: Branch(name=develop, refName=refs/heads/develop)
> semver: 1.0.4-beta.0
> 
> > Task :cv
> version: 1.0.4-beta.0
> ```

It's should be `-Psemver.overrideVersion=1.0.1`

**Comment by SettingDust** [comment]
fixed with `./gradlew test -Psemver.overrideVersion=${{ github.ref_name }}`
